<script src="<?php echo url('/')?>/assets/vendors/jquery/dist/jquery.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/axios/dist/axios.min.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/jquery-form/dist/jquery.form.min.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/popper.js/dist/umd/popper.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/js-cookie/src/js.cookie.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/moment/min/moment.min.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/tooltip.js/dist/umd/tooltip.min.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/perfect-scrollbar/dist/perfect-scrollbar.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/sticky-js/dist/sticky.min.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/wnumb/wNumb.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/jquery-validation/dist/additional-methods.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/custom/jquery-validation.init.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/dropzone/dist/dropzone.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/custom/dropzone.init.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/toastr/build/toastr.min.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/sweetalert2/dist/sweetalert2.min.js" type="text/javascript"></script>
<script src="<?php echo url('/')?>/assets/vendors/custom/sweetalert2.init.js" type="text/javascript"></script>